/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdSdkKeysIndexRouteImport } from './routes/_authenticated/projects/$projectId/sdk-keys/index'
import { Route as AuthenticatedProjectsProjectIdFlagsIndexRouteImport } from './routes/_authenticated/projects/$projectId/flags/index'
import { Route as AuthenticatedProjectsProjectIdEnvironmentsIndexRouteImport } from './routes/_authenticated/projects/$projectId/environments/index'
import { Route as AuthenticatedProjectsProjectIdFlagsNewRouteImport } from './routes/_authenticated/projects/$projectId/flags/new'
import { Route as AuthenticatedProjectsProjectIdFlagsFlagIdRouteImport } from './routes/_authenticated/projects/$projectId/flags/$flagId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdSdkKeysIndexRoute =
  AuthenticatedProjectsProjectIdSdkKeysIndexRouteImport.update({
    id: '/projects/$projectId/sdk-keys/',
    path: '/projects/$projectId/sdk-keys/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdFlagsIndexRoute =
  AuthenticatedProjectsProjectIdFlagsIndexRouteImport.update({
    id: '/projects/$projectId/flags/',
    path: '/projects/$projectId/flags/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdEnvironmentsIndexRoute =
  AuthenticatedProjectsProjectIdEnvironmentsIndexRouteImport.update({
    id: '/projects/$projectId/environments/',
    path: '/projects/$projectId/environments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdFlagsNewRoute =
  AuthenticatedProjectsProjectIdFlagsNewRouteImport.update({
    id: '/projects/$projectId/flags/new',
    path: '/projects/$projectId/flags/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdFlagsFlagIdRoute =
  AuthenticatedProjectsProjectIdFlagsFlagIdRouteImport.update({
    id: '/projects/$projectId/flags/$flagId',
    path: '/projects/$projectId/flags/$flagId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/flags/$flagId': typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
  '/projects/$projectId/flags/new': typeof AuthenticatedProjectsProjectIdFlagsNewRoute
  '/projects/$projectId/environments/': typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  '/projects/$projectId/flags/': typeof AuthenticatedProjectsProjectIdFlagsIndexRoute
  '/projects/$projectId/sdk-keys/': typeof AuthenticatedProjectsProjectIdSdkKeysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/flags/$flagId': typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
  '/projects/$projectId/flags/new': typeof AuthenticatedProjectsProjectIdFlagsNewRoute
  '/projects/$projectId/environments': typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  '/projects/$projectId/flags': typeof AuthenticatedProjectsProjectIdFlagsIndexRoute
  '/projects/$projectId/sdk-keys': typeof AuthenticatedProjectsProjectIdSdkKeysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/flags/$flagId': typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
  '/_authenticated/projects/$projectId/flags/new': typeof AuthenticatedProjectsProjectIdFlagsNewRoute
  '/_authenticated/projects/$projectId/environments/': typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  '/_authenticated/projects/$projectId/flags/': typeof AuthenticatedProjectsProjectIdFlagsIndexRoute
  '/_authenticated/projects/$projectId/sdk-keys/': typeof AuthenticatedProjectsProjectIdSdkKeysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/flags/$flagId'
    | '/projects/$projectId/flags/new'
    | '/projects/$projectId/environments/'
    | '/projects/$projectId/flags/'
    | '/projects/$projectId/sdk-keys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/flags/$flagId'
    | '/projects/$projectId/flags/new'
    | '/projects/$projectId/environments'
    | '/projects/$projectId/flags'
    | '/projects/$projectId/sdk-keys'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/projects/new'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/flags/$flagId'
    | '/_authenticated/projects/$projectId/flags/new'
    | '/_authenticated/projects/$projectId/environments/'
    | '/_authenticated/projects/$projectId/flags/'
    | '/_authenticated/projects/$projectId/sdk-keys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/sdk-keys/': {
      id: '/_authenticated/projects/$projectId/sdk-keys/'
      path: '/projects/$projectId/sdk-keys'
      fullPath: '/projects/$projectId/sdk-keys/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSdkKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/flags/': {
      id: '/_authenticated/projects/$projectId/flags/'
      path: '/projects/$projectId/flags'
      fullPath: '/projects/$projectId/flags/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFlagsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/environments/': {
      id: '/_authenticated/projects/$projectId/environments/'
      path: '/projects/$projectId/environments'
      fullPath: '/projects/$projectId/environments/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/flags/new': {
      id: '/_authenticated/projects/$projectId/flags/new'
      path: '/projects/$projectId/flags/new'
      fullPath: '/projects/$projectId/flags/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFlagsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/flags/$flagId': {
      id: '/_authenticated/projects/$projectId/flags/$flagId'
      path: '/projects/$projectId/flags/$flagId'
      fullPath: '/projects/$projectId/flags/$flagId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFlagsFlagIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdFlagsFlagIdRoute: typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
  AuthenticatedProjectsProjectIdFlagsNewRoute: typeof AuthenticatedProjectsProjectIdFlagsNewRoute
  AuthenticatedProjectsProjectIdEnvironmentsIndexRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  AuthenticatedProjectsProjectIdFlagsIndexRoute: typeof AuthenticatedProjectsProjectIdFlagsIndexRoute
  AuthenticatedProjectsProjectIdSdkKeysIndexRoute: typeof AuthenticatedProjectsProjectIdSdkKeysIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
  AuthenticatedProjectsProjectIdFlagsFlagIdRoute:
    AuthenticatedProjectsProjectIdFlagsFlagIdRoute,
  AuthenticatedProjectsProjectIdFlagsNewRoute:
    AuthenticatedProjectsProjectIdFlagsNewRoute,
  AuthenticatedProjectsProjectIdEnvironmentsIndexRoute:
    AuthenticatedProjectsProjectIdEnvironmentsIndexRoute,
  AuthenticatedProjectsProjectIdFlagsIndexRoute:
    AuthenticatedProjectsProjectIdFlagsIndexRoute,
  AuthenticatedProjectsProjectIdSdkKeysIndexRoute:
    AuthenticatedProjectsProjectIdSdkKeysIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
